// @ts-check
// Locked information architecture — see the plan file.
// Slugs are brand-neutral: no "mcp-for-unity" / "unity-mcp" in any URL.
// Pages flagged TODO land in later milestones (M3 generator, M4 net-new).
// Keep the structure stable to avoid URL breakage.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'getting-started/index' },
      collapsed: false,
      items: [
        'getting-started/install',
        'getting-started/first-prompt',
        'getting-started/clients',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/cli',
        'guides/cli-examples',
        'guides/client-configurators',
        'guides/cursor',
        'guides/remote-server-auth',
        'guides/custom-tools',
        'guides/multi-instance',
        'guides/tool-groups',
        'guides/roslyn',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Tools',
          link: { type: 'doc', id: 'reference/tools/index' },
          // Auto-derived from website/docs/reference/tools/<group>/*.md
          // The generator (tools/generate_docs_reference.py) keeps these
          // files in sync with the Python @mcp_for_unity_tool registry.
          items: [{ type: 'autogenerated', dirName: 'reference/tools' }],
        },
        {
          type: 'doc',
          id: 'reference/resources/index',
          label: 'Resources',
        },
        // 'reference/cli',      // M4
        // 'reference/manifest', // M4
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [
        'architecture/transports',
        'architecture/python-layers',
        'architecture/unity-compat',
        'architecture/remote-auth',
        'architecture/telemetry',
        'architecture/manage-physics',
        'architecture/roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: true,
      items: [
        'contributing/dev-setup',
        'contributing/testing',
        'contributing/releases',
        'contributing/docs',
      ],
    },
    {
      type: 'category',
      label: 'Migrations',
      collapsed: true,
      items: [
        'migrations/v5',
        'migrations/v6',
        'migrations/v8',
      ],
    },
    'releases',
  ],
};

export default sidebars;
